/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import FilesTracksBody from './model/FilesTracksBody';
import GitProjectDto from './model/GitProjectDto';
import SkillCategoryDto from './model/SkillCategoryDto';
import SkillDto from './model/SkillDto';
import SkillProgressDto from './model/SkillProgressDto';
import SkillTreeDto from './model/SkillTreeDto';
import TagDto from './model/TagDto';
import Tooltip from './model/Tooltip';
import TrackDto from './model/TrackDto';
import BasicSkillListApiControllerApi from './api/BasicSkillListApiControllerApi';
import ProjectsApiControllerApi from './api/ProjectsApiControllerApi';
import SkillTreeApiControllerApi from './api/SkillTreeApiControllerApi';
import TrackFileApiControllerApi from './api/TrackFileApiControllerApi';
import TracksApiControllerApi from './api/TracksApiControllerApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The FilesTracksBody model constructor.
     * @property {module:model/FilesTracksBody}
     */
    FilesTracksBody,

    /**
     * The GitProjectDto model constructor.
     * @property {module:model/GitProjectDto}
     */
    GitProjectDto,

    /**
     * The SkillCategoryDto model constructor.
     * @property {module:model/SkillCategoryDto}
     */
    SkillCategoryDto,

    /**
     * The SkillDto model constructor.
     * @property {module:model/SkillDto}
     */
    SkillDto,

    /**
     * The SkillProgressDto model constructor.
     * @property {module:model/SkillProgressDto}
     */
    SkillProgressDto,

    /**
     * The SkillTreeDto model constructor.
     * @property {module:model/SkillTreeDto}
     */
    SkillTreeDto,

    /**
     * The TagDto model constructor.
     * @property {module:model/TagDto}
     */
    TagDto,

    /**
     * The Tooltip model constructor.
     * @property {module:model/Tooltip}
     */
    Tooltip,

    /**
     * The TrackDto model constructor.
     * @property {module:model/TrackDto}
     */
    TrackDto,

    /**
    * The BasicSkillListApiControllerApi service constructor.
    * @property {module:api/BasicSkillListApiControllerApi}
    */
    BasicSkillListApiControllerApi,

    /**
    * The ProjectsApiControllerApi service constructor.
    * @property {module:api/ProjectsApiControllerApi}
    */
    ProjectsApiControllerApi,

    /**
    * The SkillTreeApiControllerApi service constructor.
    * @property {module:api/SkillTreeApiControllerApi}
    */
    SkillTreeApiControllerApi,

    /**
    * The TrackFileApiControllerApi service constructor.
    * @property {module:api/TrackFileApiControllerApi}
    */
    TrackFileApiControllerApi,

    /**
    * The TracksApiControllerApi service constructor.
    * @property {module:api/TracksApiControllerApi}
    */
    TracksApiControllerApi
};
