/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FilesTracksBody model module.
 * @module model/FilesTracksBody
 * @version v0
 */
export default class FilesTracksBody {
  /**
   * Constructs a new <code>FilesTracksBody</code>.
   * @alias module:model/FilesTracksBody
   * @class
   * @param file {Blob} 
   */
  constructor(file) {
    this.file = file;
  }

  /**
   * Constructs a <code>FilesTracksBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilesTracksBody} obj Optional instance to populate.
   * @return {module:model/FilesTracksBody} The populated <code>FilesTracksBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FilesTracksBody();
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} file
 */
FilesTracksBody.prototype.file = undefined;

