/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GitProjectDto model module.
 * @module model/GitProjectDto
 * @version v0
 */
export default class GitProjectDto {
  /**
   * Constructs a new <code>GitProjectDto</code>.
   * @alias module:model/GitProjectDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GitProjectDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GitProjectDto} obj Optional instance to populate.
   * @return {module:model/GitProjectDto} The populated <code>GitProjectDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GitProjectDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('techStack'))
        obj.techStack = ApiClient.convertToType(data['techStack'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GitProjectDto.prototype.id = undefined;

/**
 * @member {String} name
 */
GitProjectDto.prototype.name = undefined;

/**
 * @member {String} description
 */
GitProjectDto.prototype.description = undefined;

/**
 * @member {String} techStack
 */
GitProjectDto.prototype.techStack = undefined;

/**
 * @member {String} image
 */
GitProjectDto.prototype.image = undefined;

/**
 * @member {String} url
 */
GitProjectDto.prototype.url = undefined;

