/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SkillProgressDto model module.
 * @module model/SkillProgressDto
 * @version v0
 */
export default class SkillProgressDto {
  /**
   * Constructs a new <code>SkillProgressDto</code>.
   * @alias module:model/SkillProgressDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SkillProgressDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SkillProgressDto} obj Optional instance to populate.
   * @return {module:model/SkillProgressDto} The populated <code>SkillProgressDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SkillProgressDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('progress'))
        obj.progress = ApiClient.convertToType(data['progress'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
SkillProgressDto.prototype.id = undefined;

/**
 * @member {String} name
 */
SkillProgressDto.prototype.name = undefined;

/**
 * @member {Blob} progress
 */
SkillProgressDto.prototype.progress = undefined;

