/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SkillDto from './SkillDto';

/**
 * The SkillTreeDto model module.
 * @module model/SkillTreeDto
 * @version v0
 */
export default class SkillTreeDto {
  /**
   * Constructs a new <code>SkillTreeDto</code>.
   * Skill tree model containing a list of skills and their identifier
   * @alias module:model/SkillTreeDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SkillTreeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SkillTreeDto} obj Optional instance to populate.
   * @return {module:model/SkillTreeDto} The populated <code>SkillTreeDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SkillTreeDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('skillList'))
        obj.skillList = ApiClient.convertToType(data['skillList'], [SkillDto]);
    }
    return obj;
  }
}

/**
 * Unique identifier of the skill tree
 * @member {String} id
 */
SkillTreeDto.prototype.id = undefined;

/**
 * Name of the skill tree
 * @member {String} name
 */
SkillTreeDto.prototype.name = undefined;

/**
 * List of skills in the tree
 * @member {Array.<module:model/SkillDto>} skillList
 */
SkillTreeDto.prototype.skillList = undefined;

