/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TagDto model module.
 * @module model/TagDto
 * @version v0
 */
export default class TagDto {
  /**
   * Constructs a new <code>TagDto</code>.
   * @alias module:model/TagDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TagDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagDto} obj Optional instance to populate.
   * @return {module:model/TagDto} The populated <code>TagDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('icon'))
        obj.icon = ApiClient.convertToType(data['icon'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
TagDto.prototype.id = undefined;

/**
 * @member {String} name
 */
TagDto.prototype.name = undefined;

/**
 * @member {String} icon
 */
TagDto.prototype.icon = undefined;

