/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Tooltip model module.
 * @module model/Tooltip
 * @version v0
 */
export default class Tooltip {
  /**
   * Constructs a new <code>Tooltip</code>.
   * Tooltip model
   * @alias module:model/Tooltip
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Tooltip</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tooltip} obj Optional instance to populate.
   * @return {module:model/Tooltip} The populated <code>Tooltip</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tooltip();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * Tooltip description
 * @member {String} content
 */
Tooltip.prototype.content = undefined;

