/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TagDto from './TagDto';

/**
 * The TrackDto model module.
 * @module model/TrackDto
 * @version v0
 */
export default class TrackDto {
  /**
   * Constructs a new <code>TrackDto</code>.
   * @alias module:model/TrackDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackDto} obj Optional instance to populate.
   * @return {module:model/TrackDto} The populated <code>TrackDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('tagDtos'))
        obj.tagDtos = ApiClient.convertToType(data['tagDtos'], [TagDto]);
      if (data.hasOwnProperty('fileUrl'))
        obj.fileUrl = ApiClient.convertToType(data['fileUrl'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
TrackDto.prototype.id = undefined;

/**
 * @member {String} title
 */
TrackDto.prototype.title = undefined;

/**
 * @member {String} description
 */
TrackDto.prototype.description = undefined;

/**
 * @member {Number} duration
 */
TrackDto.prototype.duration = undefined;

/**
 * @member {Array.<module:model/TagDto>} tagDtos
 */
TrackDto.prototype.tagDtos = undefined;

/**
 * @member {String} fileUrl
 */
TrackDto.prototype.fileUrl = undefined;

/**
 * @member {Blob} image
 */
TrackDto.prototype.image = undefined;

